spring.main.allow-bean-definition-overriding=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.url=jdbc:h2:mem:realtestdb
spring.sql.init.mode=never

# реальные настройки OpenAI API
chatgpt.api.url=https://api.openai.com/v1/chat/completions
whisper.api.url=https://api.openai.com/v1/audio/transcriptions
chatgpt.api.key=${CHATGPT_API_KEY}
JWT_SECRET=${JWT_SECRET}

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect